// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDwcsptRw_AZyRyVgXMZLCpH-QR5nkTVI',
    appId: '1:913270259082:web:c9f4bbac217fc2f268dc73',
    messagingSenderId: '913270259082',
    projectId: 'genzbrain-e1663',
    authDomain: 'genzbrain-e1663.firebaseapp.com',
    storageBucket: 'genzbrain-e1663.firebasestorage.app',
    measurementId: 'G-KMHN7N4XLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUDv2ScvfDH44WO7eRlMUEO641DdqewI',
    appId: '1:913270259082:android:22099a8bb712805d68dc73',
    messagingSenderId: '913270259082',
    projectId: 'genzbrain-e1663',
    storageBucket: 'genzbrain-e1663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLwXt08zkTDBFzz_pDxKq-anaZMQzJyMo',
    appId: '1:913270259082:ios:6a92c8ac59d5d86468dc73',
    messagingSenderId: '913270259082',
    projectId: 'genzbrain-e1663',
    storageBucket: 'genzbrain-e1663.firebasestorage.app',
    iosBundleId: 'com.example.simson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLwXt08zkTDBFzz_pDxKq-anaZMQzJyMo',
    appId: '1:913270259082:ios:6a92c8ac59d5d86468dc73',
    messagingSenderId: '913270259082',
    projectId: 'genzbrain-e1663',
    storageBucket: 'genzbrain-e1663.firebasestorage.app',
    iosBundleId: 'com.example.simson',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDwcsptRw_AZyRyVgXMZLCpH-QR5nkTVI',
    appId: '1:913270259082:web:8291dc1003229e9b68dc73',
    messagingSenderId: '913270259082',
    projectId: 'genzbrain-e1663',
    authDomain: 'genzbrain-e1663.firebaseapp.com',
    storageBucket: 'genzbrain-e1663.firebasestorage.app',
    measurementId: 'G-G4XCQK1Q5Z',
  );
}
